### ISSUE TITLE
Carthage Compatibility

### ISSUE THREAD

**Issue by lfarah** [awesome-labs/LFTimePicker#1]
I'd be awesome if someone could help with Carthage Compatibility 😃

**Comment by JARMourato** [comment]
Hey @lfarah, are the schemes shared ?

**Comment by vsouza** [comment]
what about `Cartfile` ?

**Comment by lfarah** [comment]
@JARMourato They are, but I'm having problems:

This won't give me any error
<img width="410" alt="screen shot 2016-06-03 at 1 59-1 29 am" src="https://cloud.githubusercontent.com/assets/6511079/15789223/ed9626b0-297f-11e6-8469-4160a52cba67.png">

But when I try to test and install the lib via Carthage, I get this:

>  "Dependency "LFTimePicker" has no shared framework schemes"

**Comment by lfarah** [comment]
@vsouza you don't need a `Cartfile` to make the lib compatible. Cartfiles are only for when you wanna install a lib

**Comment by MacMeDan** [comment]
so what was the solution for this?

**Comment by lfarah** [comment]
@MacMeDan we're having problems with the library. Would you be interested in helping me re-organize the file structure?

**Comment by MacMeDan** [comment]
I am having the same problems but with another project and thought that is sounded really similar to this. But did not derive a solution from the conversation. Hoping you guys had found a solution. I am always rearranging file structure but I don't know that it always helps 🤗
