### ISSUE TITLE
How to change background colour , from & to time validation.

### ISSUE THREAD

**Issue by saleemkhan25** [awesome-labs/LFTimePicker#10]
Please let me know how to change the background colour and I wanted to add validation to time greater than from time (from time < to time)?

**Comment by lfarah** [comment]
Hey @saleemkhan25, thanks for using LFTimePicker! I just sent a PR adding support for more customizations, including changing background color.

Regarding the time validation, I'd love if you could send a PR fixing that. Lemme know how I can help 😉

**Comment by saleemkhan25** [comment]
Hello @lfarah, Thanks for the quick response. I am customising this plugin using the pod. Request you to please share the properties for customising and update the latest version.

**Comment by lfarah** [comment]
@saleemkhan25 I'm closing this as version 0.4 enables the customization. Please reopen the issue if you have any questions
