### ISSUE TITLE
Swift Package Manager on Readme

### ISSUE THREAD

**Issue by lfarah** [awesome-labs/LFTimePicker#3]
> What should we put on the majorVersion and MinorVersion?
#### Swift Package Manager

Add this project on your `Package.swift`

``` swift
import PackageDescription

let package = Package(
  name: "LFTimePicker"
)
```

**Comment by JARMourato** [comment]
I think for now, you can put only 

``` swift

let package = Package(
  name: "LFTimePicker"
)

```

:)

**Comment by lfarah** [comment]
Thanks @JARMourato, you're awesome!

**Comment by JARMourato** [comment]
Anytime @lfarah ;)
